### ISSUE TITLE
ImportError: No module named parse

### ISSUE THREAD

**Issue by shedali** [KarstenSchulz/twodolib#6]
Unable to add a task after install. 

pip 18.1
python 2.7.15

```bash
task2do -e 'save the world'
Traceback (most recent call last):
  File "/usr/local/bin/task2do", line 7, in <module>
    from twodolib.cli import main
  File "/usr/local/lib/python2.7/site-packages/twodolib/__init__.py", line 5, in <module>
    from .urlhelper import showall_url  # noqa
  File "/usr/local/lib/python2.7/site-packages/twodolib/urlhelper.py", line 10, in <module>
    from urllib.parse import quote
ImportError: No module named parse
```

**Comment by KarstenSchulz** [comment]
Please make sure to use version 0.4.1 (https://pypi.org/project/twodolib/0.4.1/) with python27. I dropped python2 support in version 0.5.0 (see https://github.com/KarstenSchulz/twodolib/blob/master/HISTORY.rst).
